### ISSUE TITLE
Can't download resume.io

### ISSUE THREAD

**Issue by baangmif** [Ankan-cyber/resumeio2pdfnextjs#1]
I can't download at https://resumeio.ankanroy.in/.
This is my resume.io link : https://resume.io/r/pRw3EK65D

**Comment by Ankan-cyber** [comment]
I run the file through my system your resume is very big that's why its stuck 

warning in dev environment

**_API response exceeds 4MB. API Routes are meant to respond quickly._**

I am uploading your pdf you can download from [here](https://github.com/Ankan-cyber/resumeio2pdfnextjs/files/14141365/resume.pdf)

This app works for small resumes like 4 to 5 pages if you setup the project locally and run it then its fine but I will find some fix meantime there is you resume link you can download from [here](https://github.com/Ankan-cyber/resumeio2pdfnextjs/files/14141365/resume.pdf)
